[package]
name = "table-structure-generator"
version = "0.1.0"
authors = ["fun4wut <nihouze@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
postgres = "0.15.2"
askama = "0.8"